const express = require('express');
const ctrl = require('../controllers/supportController');
const { authenticateToken } = require('../middleware/authMiddleware');
const router = express.Router();
const isAdmin = (req,res,next) => ['admin','superadmin'].includes(req.user?.role) ? next() : res.status(403).json({ message: 'Accès refusé.' });
router.post('/',              authenticateToken, ctrl.create);
router.get('/me',             authenticateToken, ctrl.getMine);
router.get('/all',            authenticateToken, isAdmin, ctrl.getAll);
router.patch('/:id/reply',    authenticateToken, isAdmin, ctrl.reply);
router.patch('/:id/status',   authenticateToken, isAdmin, ctrl.updateStatus);
module.exports = router;
