import { createContext, useContext, useState, useEffect } from 'react';

export const LANGS = {
  fr: {
    flag: '🇫🇷', name: 'Français', dir: 'ltr',
    nav: {
      search: 'Rechercher', compare: 'Comparer', feed: 'Feed',
      rides: 'Trajets', bookings: 'Réservations', messages: 'Messages',
      friends: 'Amis', notifs: 'Notifs', profile: 'Profil',
      publish: 'Publier un trajet', dashboard: 'Dashboard conducteur',
      admin: 'Admin', logout: 'Déconnexion', login: 'Connexion',
      register: "S'inscrire", registerFull: "S'inscrire gratuitement",
      theme: 'Thème', searchPlaceholder: 'Rechercher une ville, un trajet…',
      notifications: 'Notifications', markAllRead: 'Tout marquer lu',
      noNotifs: 'Aucune notification', viewAll: 'Voir toutes les notifications',
    },
    login: {
      title: 'Connexion', subtitle: 'Accédez à votre compte AtlasWay',
      emailLabel: 'Adresse email', emailPlaceholder: 'vous@example.com',
      passwordLabel: 'Mot de passe', forgot: 'Mot de passe oublié ?',
      submit: 'Se connecter', noAccount: 'Pas encore de compte ?',
      register: 'Créer un compte', terms: "En vous connectant, vous acceptez nos conditions d'utilisation.",
      or: 'ou', errorDefault: 'Erreur de connexion', welcome: 'Connexion réussie !',
    },
    mobile: {
      search: 'Rechercher', compare: 'Comparer les transports', feed: "Fil d'actualité",
      publish: 'Publier un trajet', rides: 'Mes trajets', bookings: 'Réservations',
      messages: 'Messages', friends: 'Amis & Réseau', profile: 'Mon profil',
      admin: 'Administration', logout: 'Déconnexion', login: 'Connexion',
      registerFull: "S'inscrire gratuitement",
    },
    profileMenu: {
      profile: 'Mon profil', friends: 'Amis & Réseau', dashboard: 'Dashboard conducteur',
      publish: 'Publier un trajet', rides: 'Mes trajets', bookings: 'Réservations', messages: 'Messages',
    },
    home: {
      badge: '🇲🇦 La plateforme covoiturage #1 au Maroc · 12 000+ voyageurs',
      label: 'Voyagez · Partagez · Économisez',
      title1: 'Voyagez partout au Maroc',
      title2: 'pour moins cher.',
      desc: "Covoiturage simple, économique et sécurisé entre particuliers. Économisez jusqu'à",
      desc60: '60%',
      descEnd: 'par rapport au taxi.',
      statLabels: ['Voyageurs actifs', 'Villes connectées', 'Note moyenne', 'Économies vs taxi'],
      chips: ['Gratuit', 'Sans engagement', 'Profils vérifiés', 'Avis authentiques'],
      findRide: 'Trouver un trajet', voiceBtn: 'Voix', mapBtn: 'Carte',
      fromPh: 'Ville de départ', toPh: "Ville d'arrivée", searchBtn: 'Rechercher',
      pax1: 'passager', paxN: 'passagers', mapLoading: 'Chargement de la carte…',
      live: 'EN DIRECT', seeArrow: 'Voir →',
      popularLabel: 'Populaires', popularTitle: 'Trajets fréquents', seeAll: 'Voir tout',
      promoTitle: 'Inscrivez-vous gratuitement', promoSub: "Profitez de trajets moins chers dès aujourd'hui",
      signupFree: "S'inscrire gratuitement",
      realtimeLabel: 'En temps réel', availRides: 'Prochains trajets disponibles',
      sampleNote: 'Exemples de trajets — publiez le premier trajet réel !',
      driverTitle: 'Vous conduisez ?', publishRide: 'Publier mon trajet',
      driverSub: 'Publiez votre trajet en 2 minutes et partagez les frais. Certains conducteurs économisent',
      driverSavings: '500 DH/mois',
      howLabel: 'Simple & rapide', howTitle: 'Comment ça marche ?',
      howSub: 'Réservez votre prochain trajet en moins de 2 minutes',
      seeAvailRides: 'Voir les trajets disponibles',
      steps: [
        { title: 'Recherchez', desc: 'Entrez votre destination et la date. Des centaines de trajets disponibles partout au Maroc.' },
        { title: 'Choisissez', desc: 'Comparez les conducteurs, leurs notes et leurs tarifs avant de réserver.' },
        { title: 'Voyagez serein', desc: 'Réservation confirmée en quelques secondes. Rencontrez votre conducteur et partez !' },
      ],
      ecoLabel: 'Impact environnemental en temps réel',
      ecoTitle: 'de CO₂ évités grâce à AtlasWay',
      ecoSub: 'Chaque trajet partagé = moins de voitures sur la route. Ce compteur augmente en temps réel.',
      ecoTrees: 'arbres', ecoTreesSub: 'équivalent arbres plantés',
      ecoKmSub: 'de trajets partagés', ecoFuelSub: 'économisés en carburant',
      networkLabel: 'Réseau AtlasWay', networkTitle: 'Connecté à tout le Maroc',
      networkSub: 'Des trajets disponibles chaque jour entre toutes les grandes villes',
      calcLabel: 'Calculateur', calcTitle: 'Combien allez-vous économiser ?',
      calcSub: 'Exemple sur le trajet Casablanca → Marrakech',
      tripsMonth: 'Trajets par mois', withAtlas: 'Avec AtlasWay',
      perTrip: '/ trajet', econSave: "économisez jusqu'à", vsTaxi: 'vs taxi',
      priceLabel: 'Transparence totale', priceSub: 'Prix moyen par mode de transport',
      cheapest: 'Le moins cher ✦',
      priceSavingsNote: "✦ AtlasWay jusqu'à 73% moins cher que l'avion · 77% moins que le grand taxi",
      inspLabel: 'Inspirations', inspTitle: 'Découvrez le Maroc',
      inspSub: 'Cliquez sur une destination pour trouver un trajet', seeRidesHover: 'Voir les trajets →',
      communityLabel: 'Communauté', topDriversTitle: 'Top conducteurs',
      seeAllRides: 'Voir tous les trajets',
      trendLabel: 'Cette semaine', trendTitle: 'Destinations tendances',
      podiumLabel: 'Cette semaine', podiumTitle: 'Trajets les plus réservés',
      reservations: 'réservations', growth: 'cette semaine',
      refBadge: 'Programme de parrainage', refTitle: 'Parrainez vos amis ',
      refSub: "Partagez votre code et voyagez ensemble. Chaque parrainage vous rapproche d'un badge exclusif.",
      yourCode: 'Votre code', shareCodeNote: 'Partagez ce code à vos amis',
      joinRef: 'Rejoindre & parrainer',
      trustLabel: 'Ils nous font confiance', testTitle: 'Ce que disent nos voyageurs',
      ratingNote: 'basé sur des avis réels', darijaToggle: '🇲🇦 Darija', frToggle: '🇫🇷 Français',
      pressLabel: 'Ils parlent de nous', pressTitle: 'Vu dans la presse marocaine',
      safeLabel: 'Sécurité & confiance', safeTitle: 'Votre sécurité, notre priorité',
      trustFeatures: [
        { title: 'Profils vérifiés', desc: 'Email confirmé pour chaque compte.' },
        { title: 'Données sécurisées', desc: 'Vos informations sont protégées.' },
        { title: 'Avis authentiques', desc: 'Notations réelles après chaque trajet.' },
        { title: 'Support réactif', desc: 'Équipe disponible 7j/7.' },
      ],
      compareBadge: 'Fonctionnalité unique au Maroc',
      compareTitle: 'Comparez tous les transports',
      compareSub: "Covoiturage · Train ONCF · Bus CTM · Grand Taxi · Avion — tout en un coup d'œil",
      compareNow: 'Comparer maintenant',
      faqLabel: 'Questions fréquentes', faqTitle: 'Vous avez des questions ?',
      faqSub: 'Tout ce que vous devez savoir avant de commencer',
      faqs: [
        { q: "C'est gratuit de s'inscrire ?", a: "Oui, l'inscription et la recherche de trajets sont totalement gratuites. Vous payez uniquement la participation aux frais directement au conducteur." },
        { q: 'Comment sont vérifiés les conducteurs ?', a: 'Chaque conducteur doit confirmer son adresse email. Les passagers peuvent ensuite laisser des avis après chaque trajet.' },
        { q: 'Que se passe-t-il si le conducteur annule ?', a: "Vous recevez une notification immédiate et pouvez rechercher un autre trajet. Nous recommandons de réserver quelques jours à l'avance." },
        { q: 'Comment contacter mon conducteur / passager ?', a: 'Une messagerie intégrée est disponible directement sur la plateforme dès que votre réservation est confirmée.' },
        { q: 'Puis-je proposer mon propre trajet ?', a: 'Absolument ! Tout utilisateur peut publier un trajet. Indiquez votre itinéraire, le prix par place et le nombre de places disponibles.' },
      ],
      joinCommunity: 'Rejoignez la communauté',
      finalTitle1: 'Prêt à voyager', finalTitle2: 'autrement ?',
      finalSub: 'Inscription gratuite · Sans engagement · 12 000+ voyageurs satisfaits',
      createAccount: "Créer mon compte — C'est gratuit", seeRidesFinal: 'Voir les trajets',
      departure: 'Départ', arrival: 'Arrivée',
      seat: 'place dispo', seats: 'places dispo', perPerson: '/pers', verified: '✦ Vérifié',
      eidTitle: 'Aïd Al-Adha 2026 — Planifiez votre trajet en famille !',
      eidSub: 'Des milliers de Marocains voyagent · Réservez avant qu\'il soit trop tard',
      days: 'jours',
    },
  },

  ar: {
    flag: '🇲🇦', name: 'العربية', dir: 'rtl',
    nav: {
      search: 'بحث', compare: 'مقارنة', feed: 'الأخبار',
      rides: 'رحلاتي', bookings: 'الحجوزات', messages: 'الرسائل',
      friends: 'الأصدقاء', notifs: 'إشعارات', profile: 'الملف',
      publish: 'نشر رحلة', dashboard: 'لوحة تحكم السائق',
      admin: 'الإدارة', logout: 'تسجيل الخروج', login: 'تسجيل الدخول',
      register: 'إنشاء حساب', registerFull: 'إنشاء حساب مجاني',
      theme: 'المظهر', searchPlaceholder: '…ابحث عن مدينة أو رحلة',
      notifications: 'الإشعارات', markAllRead: 'تعليم الكل كمقروء',
      noNotifs: 'لا توجد إشعارات', viewAll: 'عرض كل الإشعارات',
    },
    login: {
      title: 'تسجيل الدخول', subtitle: 'ادخل إلى حسابك في AtlasWay',
      emailLabel: 'البريد الإلكتروني', emailPlaceholder: 'you@example.com',
      passwordLabel: 'كلمة المرور', forgot: 'نسيت كلمة المرور؟',
      submit: 'تسجيل الدخول', noAccount: 'ليس لديك حساب؟',
      register: 'إنشاء حساب جديد', terms: 'بتسجيل دخولك، أنت توافق على شروط الاستخدام.',
      or: 'أو', errorDefault: 'خطأ في تسجيل الدخول', welcome: '!مرحباً بعودتك',
    },
    mobile: {
      search: 'بحث', compare: 'مقارنة وسائل النقل', feed: 'الأخبار',
      publish: 'نشر رحلة', rides: 'رحلاتي', bookings: 'الحجوزات',
      messages: 'الرسائل', friends: 'الأصدقاء والشبكة', profile: 'ملفي',
      admin: 'الإدارة', logout: 'تسجيل الخروج', login: 'تسجيل الدخول',
      registerFull: 'إنشاء حساب مجاني',
    },
    profileMenu: {
      profile: 'ملفي', friends: 'الأصدقاء والشبكة', dashboard: 'لوحة تحكم السائق',
      publish: 'نشر رحلة', rides: 'رحلاتي', bookings: 'الحجوزات', messages: 'الرسائل',
    },
    home: {
      badge: '🇲🇦 منصة التنقل المشترك #1 في المغرب · 12,000+ مسافر',
      label: 'سافر · شارك · وفّر',
      title1: 'سافر في جميع أنحاء المغرب',
      title2: 'بثمن أقل.',
      desc: 'تنقل مشترك بسيط، اقتصادي وآمن بين الأفراد. وفّر حتى',
      desc60: '60%',
      descEnd: 'مقارنة بسيارة الأجرة.',
      statLabels: ['مسافر نشط', 'مدينة متصلة', 'متوسط التقييم', 'توفير مقابل التاكسي'],
      chips: ['مجاني', 'بدون التزام', 'ملفات موثقة', 'آراء حقيقية'],
      findRide: 'ابحث عن رحلة', voiceBtn: 'صوت', mapBtn: 'خريطة',
      fromPh: 'مدينة المغادرة', toPh: 'مدينة الوصول', searchBtn: 'بحث',
      pax1: 'مسافر', paxN: 'مسافرون', mapLoading: '…جارٍ تحميل الخريطة',
      live: 'مباشر', seeArrow: 'عرض ←',
      popularLabel: 'الأكثر طلباً', popularTitle: 'الرحلات الشائعة', seeAll: 'عرض الكل',
      promoTitle: 'سجّل مجاناً', promoSub: 'استمتع برحلات أرخص من اليوم',
      signupFree: 'إنشاء حساب مجاني',
      realtimeLabel: 'في الوقت الفعلي', availRides: 'الرحلات القادمة المتاحة',
      sampleNote: 'أمثلة على الرحلات — انشر أول رحلة حقيقية!',
      driverTitle: 'أنت سائق؟', publishRide: 'انشر رحلتي',
      driverSub: 'انشر رحلتك في دقيقتين وشارك التكاليف. بعض السائقين يوفرون',
      driverSavings: '500 درهم/شهر',
      howLabel: 'بسيط وسريع', howTitle: 'كيف يعمل؟',
      howSub: 'احجز رحلتك القادمة في أقل من دقيقتين',
      seeAvailRides: 'عرض الرحلات المتاحة',
      steps: [
        { title: 'ابحث', desc: 'أدخل وجهتك والتاريخ. مئات الرحلات المتاحة في جميع أنحاء المغرب.' },
        { title: 'اختر', desc: 'قارن السائقين وتقييماتهم وأسعارهم قبل الحجز.' },
        { title: 'سافر بأمان', desc: 'تأكيد الحجز في ثوانٍ. التقِ بسائقك وانطلق!' },
      ],
      ecoLabel: 'الأثر البيئي في الوقت الفعلي',
      ecoTitle: 'من CO₂ تم تجنبه بفضل AtlasWay',
      ecoSub: 'كل رحلة مشتركة = سيارات أقل على الطريق. هذا العداد يزيد في الوقت الفعلي.',
      ecoTrees: 'أشجار', ecoTreesSub: 'ما يعادل أشجار مزروعة',
      ecoKmSub: 'من الرحلات المشتركة', ecoFuelSub: 'توفير في الوقود',
      networkLabel: 'شبكة AtlasWay', networkTitle: 'متصل بكل المغرب',
      networkSub: 'رحلات متاحة كل يوم بين جميع المدن الكبرى',
      calcLabel: 'حاسبة التوفير', calcTitle: 'كم ستوفر؟',
      calcSub: 'مثال على رحلة الدار البيضاء → مراكش',
      tripsMonth: 'رحلات في الشهر', withAtlas: 'مع AtlasWay',
      perTrip: '/ رحلة', econSave: 'وفّر حتى', vsTaxi: 'مقابل التاكسي',
      priceLabel: 'شفافية تامة', priceSub: 'متوسط السعر حسب وسيلة النقل',
      cheapest: 'الأرخص ✦',
      priceSavingsNote: '✦ AtlasWay حتى 73% أرخص من الطائرة · 77% أرخص من سيارة الأجرة الكبيرة',
      inspLabel: 'إلهام', inspTitle: 'اكتشف المغرب',
      inspSub: 'انقر على وجهة للعثور على رحلة', seeRidesHover: 'عرض الرحلات ←',
      communityLabel: 'المجتمع', topDriversTitle: 'أفضل السائقين',
      seeAllRides: 'عرض كل الرحلات',
      trendLabel: 'هذا الأسبوع', trendTitle: 'الوجهات الرائجة',
      podiumLabel: 'هذا الأسبوع', podiumTitle: 'الرحلات الأكثر حجزاً',
      reservations: 'حجوزات', growth: 'هذا الأسبوع',
      refBadge: 'برنامج الإحالة', refTitle: 'ادعُ أصدقاءك',
      refSub: 'شارك كودك وسافروا معاً. كل إحالة تقربك من شارة حصرية.',
      yourCode: 'كودك', shareCodeNote: 'شارك هذا الكود مع أصدقائك',
      joinRef: 'انضم وأحِل',
      trustLabel: 'يثقون بنا', testTitle: 'ماذا يقول مسافرونا',
      ratingNote: 'بناءً على آراء حقيقية', darijaToggle: '🇲🇦 الدارجة', frToggle: '🇫🇷 الفرنسية',
      pressLabel: 'يتحدثون عنا', pressTitle: 'في الصحافة المغربية',
      safeLabel: 'الأمان والثقة', safeTitle: 'سلامتك أولويتنا',
      trustFeatures: [
        { title: 'ملفات موثقة', desc: 'بريد إلكتروني مؤكد لكل حساب.' },
        { title: 'بيانات محمية', desc: 'معلوماتك في أمان تام.' },
        { title: 'آراء حقيقية', desc: 'تقييمات فعلية بعد كل رحلة.' },
        { title: 'دعم سريع', desc: 'فريقنا متاح 7 أيام/7.' },
      ],
      compareBadge: 'ميزة فريدة في المغرب',
      compareTitle: 'قارن جميع وسائل النقل',
      compareSub: 'تنقل مشترك · قطار · حافلة · تاكسي · طائرة — دفعة واحدة',
      compareNow: 'قارن الآن',
      faqLabel: 'الأسئلة الشائعة', faqTitle: 'هل لديك أسئلة؟',
      faqSub: 'كل ما تحتاج معرفته قبل البدء',
      faqs: [
        { q: 'هل التسجيل مجاني؟', a: 'نعم، التسجيل والبحث عن الرحلات مجاني تماماً. تدفع فقط مشاركة التكاليف مباشرة للسائق.' },
        { q: 'كيف يتم التحقق من السائقين؟', a: 'يجب على كل سائق تأكيد بريده الإلكتروني. يمكن للركاب بعد ذلك تقييم الرحلة.' },
        { q: 'ماذا يحدث إذا ألغى السائق؟', a: 'ستتلقى إشعاراً فورياً ويمكنك البحث عن رحلة أخرى. ننصح بالحجز قبل أيام.' },
        { q: 'كيف أتواصل مع السائق / الراكب؟', a: 'تتوفر رسائل مدمجة على المنصة فور تأكيد حجزك.' },
        { q: 'هل يمكنني نشر رحلتي الخاصة؟', a: 'بالطبع! يمكن لأي مستخدم نشر رحلة. حدد مسارك والسعر وعدد المقاعد.' },
      ],
      joinCommunity: 'انضم إلى المجتمع',
      finalTitle1: 'مستعد للسفر', finalTitle2: 'بطريقة مختلفة؟',
      finalSub: 'تسجيل مجاني · بدون التزام · +12,000 مسافر راضٍ',
      createAccount: 'إنشاء حسابي — مجاناً', seeRidesFinal: 'عرض الرحلات',
      departure: 'المغادرة', arrival: 'الوصول',
      seat: 'مقعد متاح', seats: 'مقاعد متاحة', perPerson: '/شخص', verified: '✦ موثق',
      eidTitle: 'عيد الأضحى 2026 — خطّط لرحلة عائلية!',
      eidSub: 'آلاف المغاربة يسافرون · احجز قبل فوات الأوان',
      days: 'أيام',
    },
  },

  darija: {
    flag: '🇲🇦', name: 'الدارجة', dir: 'rtl',
    nav: {
      search: 'قلب', compare: 'قارن', feed: 'الأخبار',
      rides: 'ترحالي', bookings: 'الحجوزات', messages: 'الرسايل',
      friends: 'الأصحاب', notifs: 'إشعارات', profile: 'البروفايل',
      publish: 'نشر تراحيل', dashboard: 'لوحة ديال السائق',
      admin: 'الإدارة', logout: 'خروج', login: 'دخول',
      register: 'سجل دابا', registerFull: 'سجل بالمجان',
      theme: 'الثيم', searchPlaceholder: '…قلب على مدينة ولا تراحيل',
      notifications: 'الإشعارات', markAllRead: 'اقرأ الكل',
      noNotifs: 'ما كاين والو', viewAll: 'شوف كل الإشعارات',
    },
    login: {
      title: 'سجل دخولك', subtitle: 'دخل لحسابك ديال AtlasWay',
      emailLabel: 'الإيميل ديالك', emailPlaceholder: 'you@example.com',
      passwordLabel: 'كلمة السر', forgot: 'نسيت كلمة السر؟',
      submit: 'دخل', noAccount: 'ماعندكش حساب؟',
      register: 'دير حساب جديد', terms: 'كتسجل دخولك، كتقبل الشروط ديالنا.',
      or: 'ولا', errorDefault: 'كاين مشكل فتسجيل الدخول', welcome: '!مرحبا بيك',
    },
    mobile: {
      search: 'قلب', compare: 'قارن وسائل النقل', feed: 'الأخبار',
      publish: 'نشر تراحيل', rides: 'ترحالي', bookings: 'الحجوزات',
      messages: 'الرسايل', friends: 'الأصحاب', profile: 'بروفايلي',
      admin: 'الإدارة', logout: 'خروج', login: 'دخول',
      registerFull: 'سجل بالمجان',
    },
    profileMenu: {
      profile: 'بروفايلي', friends: 'الأصحاب', dashboard: 'لوحة ديال السائق',
      publish: 'نشر تراحيل', rides: 'ترحالي', bookings: 'الحجوزات', messages: 'الرسايل',
    },
    home: {
      badge: '🇲🇦 البلاتفورم #1 ديال الكوفواتوراج فالمغرب · +12,000 مسافر',
      label: 'سافر · شارك · وفر الفلوس',
      title1: 'سافر فكل بلاد المغرب',
      title2: 'برخص.',
      desc: 'كوفواتوراج سهل، ارخص وآمن بين الناس. وفر حتى',
      desc60: '60%',
      descEnd: 'مقارنة بالطاكسي.',
      statLabels: ['مسافر نشط', 'مدينة متوصلة', 'معدل التنقيط', 'توفير مع الطاكسي'],
      chips: ['بالمجان', 'بلا التزام', 'پروفيلات محققة', 'آراء حقيقية'],
      findRide: 'قلب على تراحيل', voiceBtn: 'صوت', mapBtn: 'الخريطة',
      fromPh: 'المدينة ديال المغادرة', toPh: 'المدينة ديال الوصول', searchBtn: 'قلب',
      pax1: 'مسافر', paxN: 'مسافرين', mapLoading: '…كيتحمل الخريطة',
      live: 'مباشر', seeArrow: 'شوف ←',
      popularLabel: 'الأكتر طلباً', popularTitle: 'التراحيل المشهورة', seeAll: 'شوف الكل',
      promoTitle: 'سجل بالمجان', promoSub: 'استافد من تراحيل ارخص من دابا',
      signupFree: 'سجل بالمجان',
      realtimeLabel: 'فالوقت الحقيقي', availRides: 'التراحيل الجاية المتاحة',
      sampleNote: 'أمتلة ديال التراحيل — نشر أول رحلة حقيقية!',
      driverTitle: 'كتسوق؟', publishRide: 'نشر ترحيلي',
      driverSub: 'نشر ترحيلك فجوج دقائق وشارك المصاريف. بعض السواقة كيوفرو',
      driverSavings: '500 درهم/شهر',
      howLabel: 'سهل وسريع', howTitle: 'كيفاش كيخدم؟',
      howSub: 'احجز ترحيلك الجاي فأقل من جوج دقائق',
      seeAvailRides: 'شوف التراحيل المتاحة',
      steps: [
        { title: 'قلب', desc: 'دخل الوجهة ديالك والتاريخ. مئات التراحيل متاحة فكل بلاد المغرب.' },
        { title: 'اختار', desc: 'قارن السواقة وتنقيطاتهم وأثمانهم قبل ما تحجز.' },
        { title: 'سافر براحة', desc: 'الحجز متأكد فثواني. لقى السائق ديالك وانطلق!' },
      ],
      ecoLabel: 'الأتر البيئي فالوقت الحقيقي',
      ecoTitle: 'ديال CO₂ اتجنبات بفضل AtlasWay',
      ecoSub: 'كل رحلة مشتركة = عربيات أقل فالطريق. هاد العداد كيزيد فالوقت الحقيقي.',
      ecoTrees: 'شجرة', ecoTreesSub: 'ما يعادل شجر مزروع',
      ecoKmSub: 'ديال التراحيل المشتركة', ecoFuelSub: 'تم توفيرهم فالكازوال',
      networkLabel: 'شبكة AtlasWay', networkTitle: 'متوصل بكل المغرب',
      networkSub: 'تراحيل متاحة كل يوم بين كل المدن الكبيرة',
      calcLabel: 'حساب التوفير', calcTitle: 'شحال غادي توفر؟',
      calcSub: 'مثال على رحلة الدار البيضاء → مراكش',
      tripsMonth: 'تراحيل فالشهر', withAtlas: 'مع AtlasWay',
      perTrip: '/ رحلة', econSave: 'وفر حتى', vsTaxi: 'مع الطاكسي',
      priceLabel: 'شفافية كاملة', priceSub: 'متوسط الثمن حسب وسيلة النقل',
      cheapest: 'الأرخص ✦',
      priceSavingsNote: '✦ AtlasWay حتى 73% أرخص من الطيارة · 77% أرخص من الطاكسي الكبير',
      inspLabel: 'إلهام', inspTitle: 'اكتشف المغرب',
      inspSub: 'كليك على بلد باش تقلب على رحلة', seeRidesHover: 'شوف التراحيل ←',
      communityLabel: 'المجتمع', topDriversTitle: 'أحسن السواقة',
      seeAllRides: 'شوف جميع التراحيل',
      trendLabel: 'هاد الأسبوع', trendTitle: 'الوجهات الرائجة',
      podiumLabel: 'هاد الأسبوع', podiumTitle: 'التراحيل الأكتر محجوزة',
      reservations: 'حجوزات', growth: 'هاد الأسبوع',
      refBadge: 'برنامج الإحالة', refTitle: 'دعو حبابك',
      refSub: 'شارك الكود ديالك وسافرو مع بعض. كل إحالة كتقربك من شارة حصرية.',
      yourCode: 'الكود ديالك', shareCodeNote: 'شارك هاد الكود مع حبابك',
      joinRef: 'انضم وأحل',
      trustLabel: 'كيثقو فينا', testTitle: 'شنو كيقولو المسافرين ديالنا',
      ratingNote: 'على أساس آراء حقيقية', darijaToggle: '🇲🇦 الدارجة', frToggle: '🇫🇷 الفرنسية',
      pressLabel: 'كيتكلمو علينا', pressTitle: 'فالصحافة المغربية',
      safeLabel: 'الأمان والتقة', safeTitle: 'سلامتك هي الأولوية',
      trustFeatures: [
        { title: 'پروفيلات محققة', desc: 'إيميل مؤكد لكل حساب.' },
        { title: 'معلومات محمية', desc: 'المعلومات ديالك فأمان.' },
        { title: 'آراء حقيقية', desc: 'تنقيطات حقيقية بعد كل رحلة.' },
        { title: 'دعم سريع', desc: 'فريقنا متوفر 7/7.' },
      ],
      compareBadge: 'ميزة فريدة فالمغرب',
      compareTitle: 'قارن جميع وسائل النقل',
      compareSub: 'كوفواتوراج · طر · كار · طاكسي · طيارة — كلهم فنفس البلاصة',
      compareNow: 'قارن دابا',
      faqLabel: 'الأسئلة الشائعة', faqTitle: 'عندك أسئلة؟',
      faqSub: 'كل ما خاصك تعرفو قبل ما تبدا',
      faqs: [
        { q: 'التسجيل بالمجان؟', a: 'إيه، التسجيل والقلبة على التراحيل بالمجان. كتخلص غير مشاركة المصاريف للسائق مباشرة.' },
        { q: 'كيفاش كيتحققو السواقة؟', a: 'كل سائق خاصه يؤكد الإيميل ديالو. بعد المسافرين يقدرو يعطيو آراء.' },
        { q: 'شنو يوقع إلا لغا السائق؟', a: 'كتوصلك إشعار فالحين وتقدر تقلب على رحلة أخرى. ننصحك تحجز قبل بيام.' },
        { q: 'كيفاش نتواصل مع السائق؟', a: 'كاين رسائل مدمجة فالبلاتفورم من بعد ما يتأكد الحجز ديالك.' },
        { q: 'نقدر ننشر الرحلة ديالي؟', a: 'بالطبع! أي مستخدم يقدر ينشر رحلة. حدد المسار والثمن وعدد المقاعد.' },
      ],
      joinCommunity: 'انضم للمجتمع',
      finalTitle1: 'مستعد تسافر', finalTitle2: 'بطريقة أخرى؟',
      finalSub: 'تسجيل بالمجان · بلا التزام · +12,000 مسافر راضي',
      createAccount: 'دير الحساب ديالي — بالمجان', seeRidesFinal: 'شوف التراحيل',
      departure: 'المغادرة', arrival: 'الوصول',
      seat: 'بلاصة متاحة', seats: 'بلاصات متاحة', perPerson: '/شخص', verified: '✦ محقق',
      eidTitle: 'عيد الأضحى 2026 — خطط للرحلة العائلية!',
      eidSub: 'آلاف المغاربة كيسافرو · احجز قبل ما يفوت الوقت',
      days: 'يام',
    },
  },

  en: {
    flag: '🇬🇧', name: 'English', dir: 'ltr',
    nav: {
      search: 'Search', compare: 'Compare', feed: 'Feed',
      rides: 'Rides', bookings: 'Bookings', messages: 'Messages',
      friends: 'Friends', notifs: 'Notifs', profile: 'Profile',
      publish: 'Post a ride', dashboard: 'Driver dashboard',
      admin: 'Admin', logout: 'Sign out', login: 'Sign in',
      register: 'Sign up', registerFull: 'Sign up for free',
      theme: 'Theme', searchPlaceholder: 'Search a city or route…',
      notifications: 'Notifications', markAllRead: 'Mark all read',
      noNotifs: 'No notifications', viewAll: 'View all notifications',
    },
    login: {
      title: 'Sign In', subtitle: 'Access your AtlasWay account',
      emailLabel: 'Email address', emailPlaceholder: 'you@example.com',
      passwordLabel: 'Password', forgot: 'Forgot password?',
      submit: 'Sign in', noAccount: "Don't have an account?",
      register: 'Create account', terms: 'By signing in, you accept our terms of service.',
      or: 'or', errorDefault: 'Login failed', welcome: 'Welcome back!',
    },
    mobile: {
      search: 'Search', compare: 'Compare transport', feed: 'News feed',
      publish: 'Post a ride', rides: 'My rides', bookings: 'Bookings',
      messages: 'Messages', friends: 'Friends & Network', profile: 'My profile',
      admin: 'Administration', logout: 'Sign out', login: 'Sign in',
      registerFull: 'Sign up for free',
    },
    profileMenu: {
      profile: 'My profile', friends: 'Friends & Network', dashboard: 'Driver dashboard',
      publish: 'Post a ride', rides: 'My rides', bookings: 'Bookings', messages: 'Messages',
    },
    home: {
      badge: "🇲🇦 Morocco's #1 carpooling platform · 12,000+ travelers",
      label: 'Travel · Share · Save',
      title1: 'Travel across Morocco',
      title2: 'for less.',
      desc: 'Simple, affordable and safe ridesharing between individuals. Save up to',
      desc60: '60%',
      descEnd: 'compared to taxis.',
      statLabels: ['Active travelers', 'Connected cities', 'Average rating', 'Savings vs taxi'],
      chips: ['Free', 'No commitment', 'Verified profiles', 'Authentic reviews'],
      findRide: 'Find a ride', voiceBtn: 'Voice', mapBtn: 'Map',
      fromPh: 'Departure city', toPh: 'Arrival city', searchBtn: 'Search',
      pax1: 'passenger', paxN: 'passengers', mapLoading: 'Loading map…',
      live: 'LIVE', seeArrow: 'See →',
      popularLabel: 'Popular', popularTitle: 'Frequent routes', seeAll: 'See all',
      promoTitle: 'Sign up for free', promoSub: 'Enjoy cheaper rides starting today',
      signupFree: 'Sign up for free',
      realtimeLabel: 'Real time', availRides: 'Upcoming available rides',
      sampleNote: 'Sample rides — post the first real ride!',
      driverTitle: 'Are you driving?', publishRide: 'Post my ride',
      driverSub: 'Post your ride in 2 minutes and share costs. Some drivers save',
      driverSavings: '500 MAD/month',
      howLabel: 'Simple & fast', howTitle: 'How does it work?',
      howSub: 'Book your next ride in under 2 minutes',
      seeAvailRides: 'See available rides',
      steps: [
        { title: 'Search', desc: 'Enter your destination and date. Hundreds of rides available across Morocco.' },
        { title: 'Choose', desc: 'Compare drivers, their ratings and fares before booking.' },
        { title: 'Travel safely', desc: 'Booking confirmed in seconds. Meet your driver and go!' },
      ],
      ecoLabel: 'Real-time environmental impact',
      ecoTitle: 'of CO₂ avoided thanks to AtlasWay',
      ecoSub: 'Every shared ride = fewer cars on the road. This counter increases in real time.',
      ecoTrees: 'trees', ecoTreesSub: 'equivalent trees planted',
      ecoKmSub: 'of shared rides', ecoFuelSub: 'saved on fuel',
      networkLabel: 'AtlasWay Network', networkTitle: 'Connected across Morocco',
      networkSub: 'Rides available every day between all major cities',
      calcLabel: 'Calculator', calcTitle: 'How much will you save?',
      calcSub: 'Example: Casablanca → Marrakech route',
      tripsMonth: 'Trips per month', withAtlas: 'With AtlasWay',
      perTrip: '/ trip', econSave: 'save up to', vsTaxi: 'vs taxi',
      priceLabel: 'Full transparency', priceSub: 'Average price by transport mode',
      cheapest: 'Cheapest ✦',
      priceSavingsNote: '✦ AtlasWay up to 73% cheaper than plane · 77% less than grand taxi',
      inspLabel: 'Inspiration', inspTitle: 'Discover Morocco',
      inspSub: 'Click a destination to find a ride', seeRidesHover: 'See rides →',
      communityLabel: 'Community', topDriversTitle: 'Top drivers',
      seeAllRides: 'See all rides',
      trendLabel: 'This week', trendTitle: 'Trending destinations',
      podiumLabel: 'This week', podiumTitle: 'Most booked routes',
      reservations: 'bookings', growth: 'this week',
      refBadge: 'Referral program', refTitle: 'Refer your friends ',
      refSub: 'Share your code and travel together. Every referral earns you an exclusive badge.',
      yourCode: 'Your code', shareCodeNote: 'Share this code with your friends',
      joinRef: 'Join & refer',
      trustLabel: 'They trust us', testTitle: 'What our travelers say',
      ratingNote: 'based on real reviews', darijaToggle: '🇲🇦 Darija', frToggle: '🇫🇷 Français',
      pressLabel: 'They talk about us', pressTitle: 'In the Moroccan press',
      safeLabel: 'Safety & trust', safeTitle: 'Your safety, our priority',
      trustFeatures: [
        { title: 'Verified profiles', desc: 'Email confirmed for every account.' },
        { title: 'Secure data', desc: 'Your information is protected.' },
        { title: 'Authentic reviews', desc: 'Real ratings after every ride.' },
        { title: 'Responsive support', desc: 'Team available 7 days/7.' },
      ],
      compareBadge: 'Unique feature in Morocco',
      compareTitle: 'Compare all transport modes',
      compareSub: 'Carpooling · ONCF Train · CTM Bus · Grand Taxi · Plane — all at once',
      compareNow: 'Compare now',
      faqLabel: 'Frequently asked questions', faqTitle: 'Have questions?',
      faqSub: 'Everything you need to know before you start',
      faqs: [
        { q: 'Is registration free?', a: 'Yes, registration and ride search are completely free. You only pay the cost share directly to the driver.' },
        { q: 'How are drivers verified?', a: 'Every driver must confirm their email address. Passengers can then leave reviews after each ride.' },
        { q: 'What happens if the driver cancels?', a: 'You receive an immediate notification and can search for another ride. We recommend booking a few days in advance.' },
        { q: 'How do I contact my driver / passenger?', a: 'An integrated messaging system is available directly on the platform once your booking is confirmed.' },
        { q: 'Can I offer my own ride?', a: 'Absolutely! Any user can post a ride. Set your route, price per seat, and available seats.' },
      ],
      joinCommunity: 'Join the community',
      finalTitle1: 'Ready to travel', finalTitle2: 'differently?',
      finalSub: 'Free registration · No commitment · 12,000+ satisfied travelers',
      createAccount: "Create my account — It's free", seeRidesFinal: 'See rides',
      departure: 'Departure', arrival: 'Arrival',
      seat: 'seat available', seats: 'seats available', perPerson: '/person', verified: '✦ Verified',
      eidTitle: 'Eid Al-Adha 2026 — Plan your family trip!',
      eidSub: 'Thousands of Moroccans travel · Book before it is too late',
      days: 'days',
    },
  },
};

const LanguageContext = createContext(null);

export function LanguageProvider({ children }) {
  const [lang, setLang] = useState(() => {
    const saved = localStorage.getItem('atlas_lang');
    if (saved && LANGS[saved]) return saved;
    const browser = navigator.language?.slice(0, 2);
    if (browser === 'ar') return 'ar';
    if (browser === 'en') return 'en';
    return 'fr';
  });

  useEffect(() => {
    localStorage.setItem('atlas_lang', lang);
    const dir = LANGS[lang]?.dir || 'ltr';
    document.documentElement.setAttribute('lang', lang);
    document.documentElement.setAttribute('dir', dir);
  }, [lang]);

  const t = LANGS[lang];
  return (
    <LanguageContext.Provider value={{ lang, setLang, t, isRTL: LANGS[lang]?.dir === 'rtl' }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  return useContext(LanguageContext);
}
